services:
  hapi:
    container_name: hapi
    image: arranhs/closedhapi:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3006:3006
    volumes:
      - ./data/workspace:/home/opencode/workspace
      - ./data/.config/opencode:/home/opencode/.config/opencode
      - ./data/.local/share/opencode:/home/opencode/.local/share/opencode
      - ~/.gitconfig:/home/opencode/.gitconfig:ro
      - ~/.config/gh/hosts.yml:/home/opencode/.config/gh/hosts.yml:ro
