services:
  closedhapi:
    container_name: closedhapi
    image: arranhs/closedhapi:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3006:3006
    volumes:
      - ./workspace:/home/agent/workspace # workspace
      - ~/.config/opencode:/home/agent/.config/opencode # opencode config
      - ~/.local/share/opencode:/home/agent/.local/share/opencode # opencode data
      - ~/.gitconfig:/home/agent/.gitconfig # git config
      - ~/.config/gh:/home/agent/.config/gh # github cli config
    environment:
      # - HAPI_LISTEN_PORT=3006
